### ISSUE TITLE
Fanshim libreelec install

### ISSUE THREAD

**Issue by exiledyorkie** [jane-t/rpi-fanshim#2]
Hi,
Firstly, thank you for the hard work of putting this together.
This is probably very basic to most but I can not get this to install. I'm on LibreElec and I've installed RPi Tools. Within LibreElec on the Pi, I've added a source, this being 'https://github.com/jane-t/rpi-fanshim' but when I go to 'install from zip' the folder is blank. 
Am I missing something blindingly obvious?
Thank you

**Comment by jane-t** [comment]
Have you copied the zip file down on to your PI?  It's not in a repository which the PI can use.

**Comment by exiledyorkie** [comment]
Hello. Sorry, I don’t understand. Should I copy the files onto the sd card?
I just wrote the github address into the source, on Kodi, as I would with any other addon. Thats not the correct way then?
So, should I download the zip onto the sd card or a usb stick?

**Comment by jane-t** [comment]
Just copy the file down in the same way you copy your media down to the PI

**Comment by exiledyorkie** [comment]
Okay, I’ll have a look into that. This is the first thing which I’ve ever done on a Pi, other than install the OS. I’m a proper noob. 
Do have to save it anywhere particular?

**Comment by exiledyorkie** [comment]
Hello, all sorted now, it was all my own doing but thank you for pointing me in the right direction. Such a simple solution as just set up a shared folder between my laptop and Kodi! Thank you for all your efforts and time.
