### ISSUE TITLE
How do I install the addon?

### ISSUE THREAD

**Issue by davidoppen** [jane-t/rpi-fanshim#3]
Hey, thanks a lot for making the addon. If I add the github repository to kodi sources, it appears to be empty.

Thanks for your help.

**Comment by jane-t** [comment]
You need to download it as a zip and then copy it on to your Raspberry Pi to install.

**Comment by aggeren** [comment]
so, we need to download the rpi-fanshim-master.zip file from the green "CLONE OR DOWNLOAD" button on this page: https://github.com/jane-t/rpi-fanshim right?
And then transport it to libreelec installation through a SMB shared folder, usb-stick or scp eg.? Then access the AddOns part of Libreelec and "add from ZIP file" and then point to the rpi-fanshim-master.zip file?

**Comment by Hessenpower01** [comment]
> so, we need to download the rpi-fanshim-master.zip file from the green "CLONE OR DOWNLOAD" button on this page: https://github.com/jane-t/rpi-fanshim right?
> And then transport it to libreelec installation through a SMB shared folder, usb-stick or scp eg.? Then access the AddOns part of Libreelec and "add from ZIP file" and then point to the rpi-fanshim-master.zip file?

That's the way it should work. But on my installation it doesn't actually ...
