### ISSUE TITLE
Audio Lag 

### ISSUE THREAD

**Issue by EnricoSanchez** [jane-t/rpi-fanshim#5]
If tvheadend an Fan shim Add-on rund at same time,
the audio is shifted by approx. 0.5-0 .. 6 sec

Pi4 4k@60hz

**Comment by Gaboris** [comment]
Sorry, I don't have any help in the matter, but I'm very interested in how you're using the Fan-shim with tvheadend?

Are you using the official TV hat that connects to the full GPIO array to connect to the TV cable or some other external method?
I'm asking because I'm planning on setting one up at home, but I'm concerned about heat and would want to add a Fan-shim in between the connectors, but no idea if that would even work or not.

**Comment by jane-t** [comment]
> If tvheadend an Fan shim Add-on rund at same time,
> the audio is shifted by approx. 0.5-0 .. 6 sec

Sorry I don't have any experience with the TV head, is it possible the cpu is running too hot and downshifting?

**Comment by EnricoSanchez** [comment]
> Sorry, I don't have any help in the matter, but I'm very interested in how you're using the Fan-shim with tvheadend?
> 
> Are you using the official TV hat that connects to the full GPIO array to connect to the TV cable or some other external method?
> I'm asking because I'm planning on setting one up at home, but I'm concerned about heat and would want to add a Fan-shim in between the connectors, but no idea if that would even work or not.

I use libreelec with tvheadend server (DVB-S) with tvheadend client for live TV /pvr

**Comment by EnricoSanchez** [comment]
> > If tvheadend an Fan shim Add-on rund at same time,
> > the audio is shifted by approx. 0.5-0 .. 6 sec
> 
> Sorry I don't have any experience with the TV head, is it possible the cpu is running too hot and downshifting?


Temperature is 50-55 ° C, CPU governor is set to on demand.  when I deactivate your addon the temperature is a little higher but no offset the audio

**Comment by jane-t** [comment]
Sorry I am not able to reproduce this and do not have the hardware to test.  Please feel free to clone and update the code.

**Comment by EnricoSanchez** [comment]
> Sorry I am not able to reproduce this and do not have the hardware to test. Please feel free to clone and update the code.

Hardware is only rpi4, tvheadend is official Libreelec Software (Libreelec repo)  if in have the skills, in would bei happy to update the code, but in think its more easy for me if in build a Hardware solution to regulate the Fan bevor ich understanding the code
